
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: namespace
  name: name
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        type: Pod
    spec:
      containers:
      - image: imagen_registry
        name: name
        env:
          - name: CONNECTION_MONGO
            valueFrom:
              configMapKeyRef:
                name: connectionmongo
                key: connection_mongo.json
          - name: PASSWORD_MONGO
            valueFrom:
              secretKeyRef:
                name: secretmongo
                key: PASSWORD
        resources:
          limits:
            cpu: "100m"
            memory: "400Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
      restartPolicy: Always
      imagePullSecrets:
        - name: acr-auth
status: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: namespace
  name: connectionmongo
data:
  connection_mongo.json: |-
    {
      "connection_name": "",
      "host": "",
      "database": "",
      "username": "",
      "password": "",
      "port": "",
    }
---
apiVersion: v1
kind: Secret
metadata:
  namespace: namespace
  name: secretmongo
type: Opaque
stringData:
    PASSWORD: ""
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: name
  namespace: namespace
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: name_deploy_yaml
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 100
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 400Mi

